---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: cloudreve-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1000Gi
  nfs:
    path: /volume4/cloudreve-data
    server: 192.168.50.112
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cloudreve-nfs
  volumeMode: Filesystem


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
  name: cloudreve-storage
  namespace: cloudreve
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeMode: Filesystem
  volumeName: cloudreve-storage
