---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: dnspod  # 填你cert-manager 注册了的方式
    kubernetes.io/tls-acme: 'true'          # true的话，cert-manager 会自动生成对应的ssl证书
    nginx.ingress.kubernetes.io/cors-allow-headers: X-Forwarded-For
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 10G
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  labels:
    app.kubernetes.io/name: cloudreve
  name: cloudreve
  namespace: cloudreve
spec:
  ingressClassName: nginx
  rules:
    - host: cloudreve.rpi4b.scjtqs.com          # 改成你自己的域名
      http:
        paths:
          - backend:
              service:
                name: cloudreve
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - cloudreve.rpi4b.scjtqs.com            # 改成你自己的域名
      secretName: cloudreve-tls

